name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.x

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'pnpm'

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile

      - name: Revert changes into the pnpm-lock.yaml file
        run: git checkout -- pnpm-lock.yaml

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          # Enable your linters here
          auto_fix: true
          eslint: true
          prettier: true